#OSX xlf
PF90 = mpif77 
PCC  = mpicc 
CFLAG=
FFLAG= -qfree=f90 -c
FLDFLAG=-L/Volumes/unix/mpi/lam/lib /usr/lib/crt1.o \
        -L/opt/ibmcmp/xlsmp/1.4/lib -L/opt/ibmcmp/xlf/8.1/lib \
        -L/usr/lib/gcc/powerpc-apple-darwin8/4.0.0 \
        -L/usr/lib/gcc/powerpc-apple-darwin8/4.0.0/../../..
FLIB=-lm -llammpio -llamf77mpi -lmpi -llam -ldl -dynamic \
     -lxlf90 -lxlopt -lxl -lxlfmath -lm -lc -lgcc -lSystem \
     /usr/lib/libSystemStubs.a
LD=/usr/bin/ld

#OSX g95 mpich2
PF90 = mpif90
PCC  = mpicc 
CFLAG=
FFLAG= -ffree-form -c
FLDFLAG=-lSystem /usr/lib/libSystemStubs.a
FLIB=
LD= mpif90

#TG IA-64
PF90 = mpif90
PCC  = mpicc 
CFLAG=
FFLAG=  -c  -free
FLDFLAG=
FLIB=
LD= mpif90
all: cexam fexam

CEXES= c_ex00 c_ex01 c_ex02 c_ex03 c_ex04 c_ex05 c_ex06 \
       c_ex07 c_ex08 c_ex09 c_ex10 c_ex11 c_ex12 c_ex13
	
FEXES= f_ex00 f_ex01 f_ex02 f_ex03 f_ex04 f_ex05 f_ex06 \
       f_ex07 f_ex08 f_ex09 f_ex10 f_ex11 f_ex12 f_ex13


cexam: $(CEXES)

fexam: $(FEXES)

mpi.o: mpi.f
	$(PF90) -c mpi.f
	
.f:
	$(PF90) $(FFLAG) $< -o $@.o
	$(LD) $(FLDFLAG) -o $@.exe $@.o $(FLIB)
	/bin/rm -f $@.o
	
	
.c:
	$(PCC) $(CFLAG) $< -o $@.exe
	/bin/rm -f $@.o
	

clean:
	rm -f *mod  $(CEXES) $(FEXES) *.err *.out f*o *.exe


tar: clean
	rm -f examples.tar
	tar -cf examples.tar *

