#!/bin/csh
#PBS -q dque
#PBS -N a_long_job_name
#PBS -l nodes=2:ppn=2
#PBS -l walltime=00:5:00
#PBS -o e3d.out
#PBS -e e3d.err
#PBS -A USE300
##PBS -k eo
#PBS -V

cd /gpfs/projects/tkaiser/mpi_tests

cp $PBS_NODEFILE nodes

setenv EXAM `ls *exe`

foreach EXE ($EXAM)
  echo time01 `date`
  echo running $EXE
  setenv OUT `echo $EXE  | sed -e "s/exe/out/"`
  mpirun  -v -machinefile $PBS_NODEFILE -np 4 ./$EXE > $OUT
  echo time02 `date`
end

