MPI_INC=/usr/local/apps/python/Python2.4.1/mpiso/include
MPI_LIB=/usr/local/apps/python/Python2.4.1/mpiso/lib/shared/libmpich.so
PYTHON=/usr/local/apps/python/Python2.4.1/include/python2.4
NUMERIC=/usr/local/apps/python/Python2.4.1/include/python2.4/Numeric
SITE=/usr/local/apps/python/Python2.4.1/lib/python2.4/site-packages/mpi
SITE2=/users/tkaiser/bin/python/lib/python2.4/site-packages/mpi

PIC=-fPIC
PIC=
default: mpi.so


mpi.so: mympimodule.c
	mkdir -p build/temp.linux-ia64-2.2
	mkdir -p build/lib.linux-ia64-2.2
	icc -cxxlib-gcc -DNDEBUG -O2 -g -D_GNU_SOURCE  $(PIC) -I$(MPI_INC) -I$(PYTHON)   -I$(NUMERIC)  -c mympimodule.c -o build/temp.linux-ia64-2.2/mympimodule.o
	icc -cxxlib-gcc   -shared build/temp.linux-ia64-2.2/mympimodule.o $(MPI_LIB)  -o build/lib.linux-ia64-2.2/mpi.so 

	cp build/*lib*/*so .

install:mpi.so
	mkdir -p $(SITE)
	cp build/*lib*/*so $(SITE)
	cp build/*lib*/*so $(SITE2)

	
clean:
	rm -rf mpi.so
	rm -rf mpi_tests/mpi.so
	rm -rf build
#	rm -rf $(SITE)

tar: clean
	tar -cf mympimod.tar makefile* mympimodule.c setupmpimod*
