#MPI_PATH and MPI_LIBS should not be needed if you use mpicc instead of gcc
MPI_PATH= /Volumes/unix/usr/local/bin/mpi/32/mpich2-1.0.6p1/gccifort10.1.007
MPI_LIBS = -lmpich -lpmpich

#has not been tested for -arch ppc
ARCH= -arch i386

PYTHON =  /System/Library/Frameworks/Python.framework/Versions/2.5

#the NULL_INIT flag forces mpi_init to be called with null values, needed for some versions of mpi
#              this will not work for mpich version 1.x.x
CFLAGS =   \
-fno-strict-aliasing -Wno-long-double -no-cpp-precomp -mno-fused-madd -fno-common -dynamic \
-DNDEBUG -DNULL_INIT -g -Os -Wall -Wstrict-prototypes -DMACOSX -I/usr/include/ffi -DENABLE_DTRACE $(ARCH)


PYINC   = $(PYTHON)/include/python2.5
INSTALL = $(PYTHON)/Extras/lib/python


BUILDDIR = build/temp.macosx-10.5-i386-2.5
LDFLAGS= -Wl,-F. -bundle -undefined dynamic_lookup  $(ARCH)

NUMPY = -DNUMPY -I/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/numpy/core/include/numpy
NUMERIC =-I/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/Numeric

#used either Numeric or numpy
NUMPATH= $(NUMERIC)


default: mpi.so


mpi.so: mympimodule.o 
#	gcc -L$(MPI_PATH)/lib $(MPI_LIBS) $(LDFLAGS) $(BUILDDIR)/mympimodule.o  -o $(BUILDDIR)/mpi.so
	mpicc $(LDFLAGS)  $(BUILDDIR)/mympimodule.o   -o $(BUILDDIR)/mpi.so

	cp $(BUILDDIR)/*so .
	cp $(BUILDDIR)/*so ../mpi_tests

	
mympimodule.o: mympimodule.c $(BUILDDIR)
#	gcc -I$(MPI_PATH)/include $(CFLAGS) -pipe $(NUMPATH)  -I$(PYINC) -c mympimodule.c -o $(BUILDDIR)/mympimodule.o
	mpicc $(CFLAGS) -pipe $(NUMPATH)  -I$(PYINC) -c mympimodule.c -o $(BUILDDIR)/mympimodule.o

solvers.o: solvers.c $(BUILDDIR)
#	gcc -I$(MPI_PATH)/include $(CFLAGS) -pipe $(NUMPATH)  -I$(PYINC) -c solvers.c -o $(BUILDDIR)/solvers.o
	mpicc $(CFLAGS) -pipe $(NUMPATH)  -I$(PYINC) -c solvers.c -o $(BUILDDIR)/solvers.o

$(BUILDDIR):
	mkdir -p $(BUILDDIR)

clean:
	rm -rf mpi.so mympimodule.o
	rm -rf ../mpi_tests/mpi.so
	rm -rf $(BUILDDIR)

tar: clean
	tar -cf mympimod.tar makefile* mympimodule.c setupmpimod*

install:default
	mkdir -p $(INSTALL)/mpi
	cp $(BUILDDIR)/*so $(INSTALL)/mpi.so


