MPI=/opt/mpich/intel/include
PYTHON=/home/tkaiser/mympi/Python2.3.3/include/python2.3

default: mpi.so


mpi.so: mympimodule.c makefile.nbcr
	mkdir -p build/temp.linux-i686-2.3
	mkdir -p build/lib.linux-i686-2.3
	icc -cxxlib-gcc -DNDEBUG -O2 -g  -march=i386 -mcpu=i686 -D_GNU_SOURCE -fPIC -fPIC -I$(MPI) -I$(PYTHON)  -c mympimodule.c -o build/temp.linux-i686-2.3/mympimodule.o
	icc -cxxlib-gcc -shared build/temp.linux-i686-2.3/mympimodule.o -L/opt/mpich/intel/lib  -lmpich -o build/lib.linux-i686-2.3/mpi.so 
	cp build/*lib*/*so .
	cp build/*lib*/*so ../mpi_tests

	
clean:
	rm -rf mpi.so
	rm -rf ../mpi_tests/mpi.so
	rm -rf build

tar: clean
	tar -cf mympimod.tar makefile mympimodule.c setupmpimod*
